package lmodeler;

/**
 *  Trida pro vyvolani okna O programu. Obsahuje i text.
 * @author Jjakub Kvita
 */
public class AboutFrame extends javax.swing.JFrame {

    private String htmlText = "<font face=\"tahoma\"size=4><p style=\"text-align: center;\" ><br><br><font size=6><b>LModeler</b></font><br><br>"
            + "Generátor 3D modelů pomocí L-systémů.<br>"
            + "Vytvořeno jako součást bakalářské práce na FIT VUT Brno v roce 2013.<br><br><br><br>"
            + "<b>Autor:</b><br><br>"
            + "<i>Jakub Kvita<br><br>"
            + "<font size=3>xkvita01@stud.fit.vutbr.cz<br>kvitajakub@gmail.com</font>";
    
    /**
     * Konstruktor.
     */
    public AboutFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textp = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("O programu");
        setResizable(false);

        textp.setEditable(false);
        textp.setContentType("text/html");
        textp.setText(htmlText);
        jScrollPane1.setViewportView(textp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textp;
    // End of variables declaration//GEN-END:variables
}
