package lmodeler;

import java.io.File;
import lsystem.LSystem;
import lsystem.LsysException;

/**
 *  Panel pro GUI vizualizaci a ovladani Lsystemu.
 * @author Jakub Kvita
 */
public class LPanel extends javax.swing.JPanel {

    /**
     * Soubor kde muze byt Lsystem ulozeny.
     */
    public File saveFile = null;
    
    private LSystem lsystem;
    private EListener listen;
            
    
    /**
     * Konstruktor.
     */
    public LPanel() {
        
        lsystem = new LSystem();
        
        initComponents();
        
        jLabelError1.setText("");
        jTextFieldAxiom.setText(lsystem.getAxiom());
        jTextFieldIgnored.setText(lsystem.getIgnoredSymbols());
        jTextFieldString.setText(lsystem.getActiveDerivation());
        jTextAreaRules.setText(lsystem.getRules());
        jSpinnerAngle.setValue(new Double(lsystem.getAngleStep()));
        jSpinnerThickness.setValue(new Double(lsystem.getThickness()));
    }
    
    
    /**
     * Konstruktor pro otevirani jiz vytvoreneho systemu.
     * @param sys 
     */
    public LPanel(LSystem sys) {
        
        lsystem = sys;
        
        initComponents();
        
        jLabelError1.setText("");
        jTextFieldAxiom.setText(lsystem.getAxiom());
        jTextFieldIgnored.setText(lsystem.getIgnoredSymbols());
        jTextFieldString.setText(lsystem.getActiveDerivation());
        jTextAreaRules.setText(lsystem.getRules());
        jSpinnerAngle.setValue(new Double(lsystem.getAngleStep()));
        jSpinnerThickness.setValue(new Double(lsystem.getThickness()));
        if(sys.getColorSet()==LSystem.COLORSET_BASIC){
            colorSetCombo.setSelectedItem("Základní");
        }
        else{
            colorSetCombo.setSelectedItem("Rozšířená");
        }
    }

    /**
     * Zmeni Lsystem se kterym se pracuje na jiny.
     * @param sys Novy Lsystem.
     */
    public void setLSys(LSystem sys){
        
        lsystem = sys;
        gLJPanel.display();
        
        jLabelError1.setText("");
        jTextFieldIgnored.setText(lsystem.getIgnoredSymbols());
        jTextFieldAxiom.setText(lsystem.getAxiom());
        jTextFieldString.setText(lsystem.getActiveDerivation());
        jTextAreaRules.setText(lsystem.getRules());
        jSpinnerAngle.setValue(new Double(lsystem.getAngleStep()));
        jSpinnerThickness.setValue(new Double(lsystem.getThickness()));
    }
    
    /**
     * Vrati Lsystem, se kterym pracuje.
     * @return Lsystem
     */
    public LSystem getLSys(){
        return lsystem;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        gLJPanel = new javax.media.opengl.awt.GLJPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldAxiom = new javax.swing.JTextField();
        jScrollPaneRules = new javax.swing.JScrollPane();
        jTextAreaRules = new javax.swing.JTextArea();
        jButtonUndo = new javax.swing.JButton();
        jButtonDo = new javax.swing.JButton();
        jSpinnerDoTo = new javax.swing.JSpinner();
        jButtonDoTo = new javax.swing.JButton();
        jButtonChange = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerAngle = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        colorSetCombo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerThickness = new javax.swing.JSpinner();
        jLabelError1 = new javax.swing.JLabel();
        jTextFieldIgnored = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerThicknessCoef = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldString = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 599));

        listen = new EListener(gLJPanel, lsystem);
        gLJPanel.addGLEventListener(listen);
        gLJPanel.addMouseListener(listen);
        gLJPanel.addMouseMotionListener(listen);
        gLJPanel.addMouseWheelListener(listen);
        gLJPanel.setPreferredSize(new java.awt.Dimension(370, 395));

        javax.swing.GroupLayout gLJPanelLayout = new javax.swing.GroupLayout(gLJPanel);
        gLJPanel.setLayout(gLJPanelLayout);
        gLJPanelLayout.setHorizontalGroup(
            gLJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        gLJPanelLayout.setVerticalGroup(
            gLJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(gLJPanel);

        jPanel1.setMinimumSize(new java.awt.Dimension(290, 560));
        jPanel1.setPreferredSize(new java.awt.Dimension(290, 560));

        jTextAreaRules.setColumns(20);
        jTextAreaRules.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextAreaRules.setRows(5);
        jTextAreaRules.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextAreaRules.setPreferredSize(new java.awt.Dimension(80, 74));
        jScrollPaneRules.setViewportView(jTextAreaRules);

        jButtonUndo.setText("Krok derivace zpět");
        jButtonUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUndoActionPerformed(evt);
            }
        });

        jButtonDo.setText("Krok derivace");
        jButtonDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });

        jSpinnerDoTo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));

        jButtonDoTo.setText("Derivace");
        jButtonDoTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoToActionPerformed(evt);
            }
        });

        jButtonChange.setText("Načíst systém");
        jButtonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Axiom");

        jLabel2.setText("Pravidla");

        jSpinnerAngle.setModel(new javax.swing.SpinnerNumberModel(25.0d, 0.0d, 359.0d, 1.0d));
        jSpinnerAngle.setToolTipText("");
        jSpinnerAngle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerAngleStateChanged(evt);
            }
        });

        jLabel3.setLabelFor(jSpinnerAngle);
        jLabel3.setText("Úhel otočení:");

        jLabel4.setLabelFor(jSpinnerDoTo);
        jLabel4.setText("Úroveň:");

        colorSetCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Základní", "Rozšířená" }));
        colorSetCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorSetComboActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Barevná sada:");

        jLabel6.setText("Počáteční tloušťka:");

        jSpinnerThickness.setModel(new javax.swing.SpinnerNumberModel(0.3d, 0.0d, 10.0d, 0.05d));
        jSpinnerThickness.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerThicknessStateChanged(evt);
            }
        });

        jLabelError1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelError1.setForeground(new java.awt.Color(204, 0, 51));
        jLabelError1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelError1.setText("Spatne!");
        jLabelError1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel7.setText("Ignorované symboly");

        jSpinnerThicknessCoef.setModel(new javax.swing.SpinnerNumberModel(0.707d, 0.0d, 10.0d, 0.05d));
        jSpinnerThicknessCoef.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerThicknessCoefStateChanged(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Koeficient tloušťky:");

        jTextFieldString.setEditable(false);
        jTextFieldString.setPreferredSize(new java.awt.Dimension(6, 27));

        jLabel9.setText("Řetězec:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAxiom)
                            .addComponent(jTextFieldIgnored)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelError1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonUndo, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(13, 13, 13)
                                        .addComponent(jSpinnerDoTo)))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonDo, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(jButtonDoTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerThicknessCoef)
                                    .addComponent(jSpinnerThickness)
                                    .addComponent(jSpinnerAngle)
                                    .addComponent(colorSetCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButtonChange, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneRules)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldIgnored, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAxiom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneRules, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButtonChange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelError1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorSetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerAngle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerThickness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinnerThicknessCoef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerDoTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDoTo)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUndo)
                    .addComponent(jButtonDo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(5, 5, 5))
        );

        jSplitPane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerThicknessStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerThicknessStateChanged
        lsystem.setThickness((Double)jSpinnerThickness.getValue());
        gLJPanel.display();
    }//GEN-LAST:event_jSpinnerThicknessStateChanged

    private void colorSetComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorSetComboActionPerformed

        if(colorSetCombo.getSelectedIndex()==0){
            lsystem.setColorSet(LSystem.COLORSET_BASIC);
        }
        else{
            lsystem.setColorSet(LSystem.COLORSET_EXTENDED);
        }
        gLJPanel.display();

    }//GEN-LAST:event_colorSetComboActionPerformed

    private void jSpinnerAngleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerAngleStateChanged
        lsystem.setAngleStep((Double)jSpinnerAngle.getValue());
        gLJPanel.display();
    }//GEN-LAST:event_jSpinnerAngleStateChanged

    private void jButtonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeActionPerformed
        jLabelError1.setText("");
        try {
            lsystem.setAxiom(jTextFieldAxiom.getText());
            lsystem.setIgnoredSymbols(jTextFieldIgnored.getText());
            lsystem.setRules(jTextAreaRules.getText());
            listen.initView();
            gLJPanel.display();
            jSpinnerDoTo.setValue(new Integer(lsystem.getActDerivation()));
            jTextFieldString.setText(lsystem.getActiveDerivation());
        } catch (LsysException ex) {
            jLabelError1.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonChangeActionPerformed

    private void jButtonDoToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoToActionPerformed
        jLabelError1.setText("");
        try {
            lsystem.derivateTo((Integer)jSpinnerDoTo.getValue());
            gLJPanel.display();
            jTextFieldString.setText(lsystem.getActiveDerivation());
        } catch (LsysException ex) {
            jLabelError1.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonDoToActionPerformed

    private void jButtonDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoActionPerformed
        jLabelError1.setText("");
        try {
            lsystem.derivateStep();
            gLJPanel.display();
            jSpinnerDoTo.setValue(new Integer(lsystem.getActDerivation()));
            jTextFieldString.setText(lsystem.getActiveDerivation());
        } catch (LsysException ex) {
            jLabelError1.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonDoActionPerformed

    private void jButtonUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUndoActionPerformed
        jLabelError1.setText("");
        try {
            lsystem.undoDerivateStep();
            gLJPanel.display();
            jSpinnerDoTo.setValue(new Integer(lsystem.getActDerivation()));
            jTextFieldString.setText(lsystem.getActiveDerivation());
        } catch (LsysException ex) {
            jLabelError1.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonUndoActionPerformed

    private void jSpinnerThicknessCoefStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerThicknessCoefStateChanged
        lsystem.setThicknessCoef((Double)jSpinnerThicknessCoef.getValue());
        gLJPanel.display();
    }//GEN-LAST:event_jSpinnerThicknessCoefStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox colorSetCombo;
    private javax.media.opengl.awt.GLJPanel gLJPanel;
    private javax.swing.JButton jButtonChange;
    private javax.swing.JButton jButtonDo;
    private javax.swing.JButton jButtonDoTo;
    private javax.swing.JButton jButtonUndo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelError1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneRules;
    private javax.swing.JSpinner jSpinnerAngle;
    private javax.swing.JSpinner jSpinnerDoTo;
    private javax.swing.JSpinner jSpinnerThickness;
    private javax.swing.JSpinner jSpinnerThicknessCoef;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTextArea jTextAreaRules;
    private javax.swing.JTextField jTextFieldAxiom;
    private javax.swing.JTextField jTextFieldIgnored;
    private javax.swing.JTextField jTextFieldString;
    // End of variables declaration//GEN-END:variables
}
