package lmodeler;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import lsystem.LSystem;
import lsystem.LsysException;


/**
 * Hlavni okno programu LModeler.
 * @author Jakub Kvita
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Pocet otevrenych zalozek za beh programu pro implicitni nazev nove zalozky.
     */
    int tabNumber = 1;
    
    
    /**
     * Konstruktor.
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();
        lPanel1 = new lmodeler.LPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNovy = new javax.swing.JMenuItem();
        jMenuItemOtevrit = new javax.swing.JMenuItem();
        jMenuItemUlozit = new javax.swing.JMenuItem();
        jMenuItemUlozitJako = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemZavriAkt = new javax.swing.JMenuItem();
        jMenuItemKonec = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemKochStar = new javax.swing.JMenuItem();
        jMenuItemSierpTriangle = new javax.swing.JMenuItem();
        jMenuItemSierpCarpet = new javax.swing.JMenuItem();
        jMenuItemDragon = new javax.swing.JMenuItem();
        jMenuItemPenrose = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemPeano = new javax.swing.JMenuItem();
        jMenuItemPeanoGosper = new javax.swing.JMenuItem();
        jMenuItemHilbert = new javax.swing.JMenuItem();
        jMenuItemHilbert3D = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemBush = new javax.swing.JMenuItem();
        jMenuItemPlant3D1 = new javax.swing.JMenuItem();
        jMenuItemPlant3D2 = new javax.swing.JMenuItem();
        jMenuItemPlant1 = new javax.swing.JMenuItem();
        jMenuItemPlant2 = new javax.swing.JMenuItem();
        jMenuItemPlant3 = new javax.swing.JMenuItem();
        jMenuItemPlant4 = new javax.swing.JMenuItem();
        jMenuItemPlant5 = new javax.swing.JMenuItem();
        jMenuItemHG1 = new javax.swing.JMenuItem();
        jMenuItemHG2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemManual = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemOProgramu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LModeler");

        tabPane.addTab("tab1", lPanel1);
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline("nový "+tabNumber++,tabPane));

        jMenu1.setText("Soubor");

        jMenuItemNovy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNovy.setText("Nový");
        jMenuItemNovy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovyActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNovy);

        jMenuItemOtevrit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemOtevrit.setText("Otevřít");
        jMenuItemOtevrit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOtevritActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOtevrit);

        jMenuItemUlozit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemUlozit.setText("Uložit");
        jMenuItemUlozit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUlozitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUlozit);

        jMenuItemUlozitJako.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemUlozitJako.setText("Uložit jako");
        jMenuItemUlozitJako.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUlozitJakoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUlozitJako);
        jMenu1.add(jSeparator1);

        jMenuItemZavriAkt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemZavriAkt.setText("Zavřít aktivní záložku");
        jMenuItemZavriAkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZavriAktActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemZavriAkt);

        jMenuItemKonec.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemKonec.setText("Konec programu");
        jMenuItemKonec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKonecActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemKonec);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Příklady");

        jMenu4.setText("Fraktály");

        jMenuItemKochStar.setText("Kochova vločka");
        jMenuItemKochStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKochStarActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemKochStar);

        jMenuItemSierpTriangle.setText("Sierpinského trojúhelník");
        jMenuItemSierpTriangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSierpTriangleActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemSierpTriangle);

        jMenuItemSierpCarpet.setText("Sierpinského koberec");
        jMenuItemSierpCarpet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSierpCarpetActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemSierpCarpet);

        jMenuItemDragon.setText("Dračí křivka");
        jMenuItemDragon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDragonActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemDragon);

        jMenuItemPenrose.setText("Penroseovo dláždění");
        jMenuItemPenrose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPenroseActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemPenrose);

        jMenu2.add(jMenu4);

        jMenu5.setText("Prostor vyplňující křivky");

        jMenuItemPeano.setText("Peanova křivka");
        jMenuItemPeano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPeanoActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemPeano);

        jMenuItemPeanoGosper.setText("Peano-Gosperova křivka");
        jMenuItemPeanoGosper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPeanoGosperActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemPeanoGosper);

        jMenuItemHilbert.setText("Hibertova křivka");
        jMenuItemHilbert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHilbertActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemHilbert);

        jMenuItemHilbert3D.setText("Hilbertova křivka ve 3D");
        jMenuItemHilbert3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHilbert3DActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemHilbert3D);

        jMenu2.add(jMenu5);

        jMenu6.setText("Rostliny");

        jMenuItemBush.setText("Keř");
        jMenuItemBush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBushActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemBush);

        jMenuItemPlant3D1.setText("Rostlina 3D .1");
        jMenuItemPlant3D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPlant3D1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemPlant3D1);

        jMenuItemPlant3D2.setText("Rostlina 3D .2");
        jMenuItemPlant3D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPlant3D2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemPlant3D2);

        jMenuItemPlant1.setText("Rostlina .1");
        jMenuItemPlant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPlant1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemPlant1);

        jMenuItemPlant2.setText("Rostlina .2");
        jMenuItemPlant2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPlant2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemPlant2);

        jMenuItemPlant3.setText("Rostlina .3");
        jMenuItemPlant3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPlant3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemPlant3);

        jMenuItemPlant4.setText("Rostlina .4");
        jMenuItemPlant4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPlant4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemPlant4);

        jMenuItemPlant5.setText("Rostlina .5");
        jMenuItemPlant5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPlant5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemPlant5);

        jMenuItemHG1.setText("Hogeweg-Hesperův model .1");
        jMenuItemHG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHG1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemHG1);

        jMenuItemHG2.setText("Hogeweg-Hesperův model .2");
        jMenuItemHG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHG2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemHG2);

        jMenu2.add(jMenu6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Nápověda");

        jMenuItemManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, 0));
        jMenuItemManual.setText("Manuál");
        jMenuItemManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManualActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemManual);
        jMenu3.add(jSeparator2);

        jMenuItemOProgramu.setText("O programu");
        jMenuItemOProgramu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOProgramuActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemOProgramu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNovyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovyActionPerformed

        //novy panel
        tabPane.addTab(null, new LPanel());
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline("nový "+tabNumber++,tabPane));
        
    }//GEN-LAST:event_jMenuItemNovyActionPerformed

    private void jMenuItemZavriAktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZavriAktActionPerformed
      
        if(tabPane.getSelectedIndex()!=-1){
                tabPane.remove(tabPane.getSelectedIndex());
        }        
    }//GEN-LAST:event_jMenuItemZavriAktActionPerformed

    private void jMenuItemUlozitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUlozitActionPerformed
        
        if(((LPanel)tabPane.getSelectedComponent()).saveFile != null){
            
            BufferedWriter out = null;
            try {
                out = new BufferedWriter(new FileWriter(((LPanel)tabPane.getSelectedComponent()).saveFile));
                out.write(((LPanel)tabPane.getSelectedComponent()).getLSys().toXML());

            } catch ( LsysException | IOException ex) {
		JOptionPane.showMessageDialog(this,"Nepovedlo se ulozit do souboru.",
					    "Error",
					    JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    out.close();
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
        else{
            saveAs();
        }
        
    }//GEN-LAST:event_jMenuItemUlozitActionPerformed

    private void jMenuItemOtevritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOtevritActionPerformed
        
        LPanel panel;
        LSystem sys;
        JFileChooser fileChooser = new JFileChooser();		
	int retval=fileChooser.showOpenDialog(this);
        
	if(retval == JFileChooser.APPROVE_OPTION){
            
                sys = new LSystem();
            
                File file = fileChooser.getSelectedFile();

            try {
                //prectu soubor
                byte[] bytes = Files.readAllBytes(file.toPath());
                //zkusim rozparsovat string a nacist
                sys.fromXML(new String(bytes,"UTF-8"));
                
            } catch (LsysException ex) {
		JOptionPane.showMessageDialog(this,ex.getMessage(),
					    "Error",
					    JOptionPane.ERROR_MESSAGE);
                return;
            } catch (FileNotFoundException e) {
		JOptionPane.showMessageDialog(this,"Soubor nebyl nalezen.",
					    "Error",
					    JOptionPane.ERROR_MESSAGE);
                return;
            } catch (IOException e) {
		JOptionPane.showMessageDialog(this,"IO error - neco se pokazilo.",
					    "Error",
					    JOptionPane.ERROR_MESSAGE);
                return;
            }            
                
            //novy panel
            panel = new LPanel(sys);
            tabPane.addTab(null, panel);
            panel.saveFile = file;
            //prepne aktivitu na vytvoreny tab
            tabPane.setSelectedIndex(tabPane.getTabCount()-1);
            //nastavim headline
            tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(file.getName(),tabPane));
        }

    }//GEN-LAST:event_jMenuItemOtevritActionPerformed

    private void jMenuItemKonecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKonecActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_jMenuItemKonecActionPerformed

    private void jMenuItemUlozitJakoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUlozitJakoActionPerformed

        saveAs();
        
    }//GEN-LAST:event_jMenuItemUlozitJakoActionPerformed

    private void jMenuItemOProgramuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOProgramuActionPerformed

        AboutFrame inst = new AboutFrame();
        inst.setLocationRelativeTo(null);
        inst.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemOProgramuActionPerformed

    private void jMenuItemManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManualActionPerformed

        HelpFrame inst = new HelpFrame();
        inst.setLocationRelativeTo(null);
        inst.setVisible(true);        
        
    }//GEN-LAST:event_jMenuItemManualActionPerformed

    private void jMenuItemKochStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKochStarActionPerformed
        
        LSystem sys = new LSystem();
        sys.setAxiom("F++F++F");
        sys.setAngleStep(60.0);
        sys.setThickness(0.05);
        sys.setColorSet(LSystem.COLORSET_EXTENDED);
        try {
            sys.setRules("F=F-F++F-F");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemKochStar.getText(),tabPane));
        
    }//GEN-LAST:event_jMenuItemKochStarActionPerformed

    private void jMenuItemSierpTriangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSierpTriangleActionPerformed
        
        LSystem sys = new LSystem();
        sys.setAxiom("L");
        sys.setAngleStep(60.0);
        sys.setThickness(0.1);
        sys.setColorSet(LSystem.COLORSET_EXTENDED);
        try {
        sys.setRules("F = 'F-L-F+L+F+L+F-L-F\n"
                           +"L = 'L+F+L-F-L-F-L+F+L\n");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemSierpTriangle.getText(),tabPane));
        
    }//GEN-LAST:event_jMenuItemSierpTriangleActionPerformed

    private void jMenuItemSierpCarpetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSierpCarpetActionPerformed
        
        LSystem sys = new LSystem();
        sys.setAxiom("F");
        sys.setAngleStep(90.0);
        sys.setThickness(0.3);
        sys.setColorSet(LSystem.COLORSET_EXTENDED);
        try {
        sys.setRules("F = 'F+F-F-F-f+F+F+F-F\n"
                + "f=fff");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemSierpCarpet.getText(),tabPane));
        
    }//GEN-LAST:event_jMenuItemSierpCarpetActionPerformed

    private void jMenuItemDragonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDragonActionPerformed
        LSystem sys = new LSystem();
        sys.setAxiom("FX");
        sys.setAngleStep(45.0);
        sys.setThickness(0.15);
        sys.setColorSet(LSystem.COLORSET_EXTENDED);
        try {
        sys.setRules("F = '\n"
                + "X = -FX++FY-\n"
                + "Y = +FX--FY+");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemDragon.getText(),tabPane));
        
    }//GEN-LAST:event_jMenuItemDragonActionPerformed

    private void jMenuItemPeanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeanoActionPerformed
        LSystem sys = new LSystem();
        sys.setAxiom("F-F-F-F");
        sys.setAngleStep(90.0);
        sys.setThickness(0.1);
        sys.setColorSet(LSystem.COLORSET_EXTENDED);
        try {
        sys.setRules("F = 'F-F+F+F+F-F-F-F+F\n");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemPeano.getText(),tabPane));
        
    }//GEN-LAST:event_jMenuItemPeanoActionPerformed

    private void jMenuItemPeanoGosperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeanoGosperActionPerformed
        LSystem sys = new LSystem();
        sys.setAxiom("FX");
        sys.setAngleStep(60.0);
        sys.setThickness(0.15);
        sys.setColorSet(LSystem.COLORSET_EXTENDED);
        try {
        sys.setRules("F = '\n"
                + "X = FX-FY--FY+FX++FXFX+FY-\n"
                + "Y = +FX-FYFY--FY-FX++FX+FY");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemPeanoGosper.getText(),tabPane));
        
    }//GEN-LAST:event_jMenuItemPeanoGosperActionPerformed

    private void jMenuItemHilbertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHilbertActionPerformed

        LSystem sys = new LSystem();
        sys.setAxiom("X");
        sys.setAngleStep(90.0);
        sys.setThickness(0.15);
        sys.setColorSet(LSystem.COLORSET_EXTENDED);
        try {
        sys.setRules("X = '-YF+XFX+FY-\n"
                + "Y = +XF-YFY-FX+");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemHilbert.getText(),tabPane));
        
    }//GEN-LAST:event_jMenuItemHilbertActionPerformed

    private void jMenuItemBushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBushActionPerformed

        LSystem sys = new LSystem();
        sys.setAxiom(",F");
        sys.setAngleStep(22.5);
        sys.setThickness(0.15);
        sys.setColorSet(LSystem.COLORSET_EXTENDED);
        try {
        sys.setRules("F = FF-['''''-F+F+F]+['''''+F-F-F]\n");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemBush.getText(),tabPane));
   
    }//GEN-LAST:event_jMenuItemBushActionPerformed

    private void jMenuItemPlant3D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPlant3D1ActionPerformed

        LSystem sys = new LSystem();
        sys.setAxiom(",[&FY!Z]/////[&FY!Z]///////[&FY!Z]");
        sys.setAngleStep(25.0);
        sys.setThickness(0.6);
        sys.setColorSet(LSystem.COLORSET_BASIC);
        try {
        sys.setRules( "Z=[&FY!Z]/////[&FY!Z]///////[&FY!Z]\n"
                + "F=X/////F\n"
                + "X=FY\n"
                + "Y=[''''^^{-'f.+,f.+f.-|-f.+'f.+f.}]\n"
                + "F=FF");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemPlant3D1.getText(),tabPane));
   
    }//GEN-LAST:event_jMenuItemPlant3D1ActionPerformed

    private void jMenuItemPlant2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPlant2ActionPerformed

        LSystem sys = new LSystem();
        sys.setAxiom("F");
        sys.setAngleStep(25.0);
        sys.setThickness(0.6);
        sys.setColorSet(LSystem.COLORSET_BASIC);
        try {
        sys.setRules( "F=0.33=F[+F]F[-F]F\n"
                + "F=0.33=F[+F]F\n"
                + "F=0.34=F[-F]F\n");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemPlant2.getText(),tabPane));
   
    }//GEN-LAST:event_jMenuItemPlant2ActionPerformed

    private void jMenuItemPlant3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPlant3ActionPerformed

        LSystem sys = new LSystem();
        sys.setAxiom("Z");
        sys.setAngleStep(50.0);
        sys.setThickness(0.8);
        sys.setColorSet(LSystem.COLORSET_EXTENDED);
        try {
        sys.setRules( "Z = '''''''ZFX['''''''!+Z]['''''''!-Z]\n"
                + "X = X[-FFF][+FFF]FX\n");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemPlant3.getText(),tabPane));
   
    }//GEN-LAST:event_jMenuItemPlant3ActionPerformed

    private void jMenuItemPlant4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPlant4ActionPerformed
   
        LSystem sys = new LSystem();
        
        sys.setAxiom("Z");
        sys.setAngleStep(35.0);
        sys.setThickness(0.3);
        sys.setColorSet(LSystem.COLORSET_BASIC);
        try {
        sys.setRules( "Z = ZFX['+Z]['-Z]\n"
                + "X = X[-FFF][+FFF]FX\n");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemPlant4.getText(),tabPane));
   
    }//GEN-LAST:event_jMenuItemPlant4ActionPerformed

    private void jMenuItemPlant3D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPlant3D2ActionPerformed

        LSystem sys = new LSystem();
        sys.setAxiom("Q");
        sys.setAngleStep(18.0);
        sys.setThickness(0.2);
        sys.setColorSet(LSystem.COLORSET_BASIC);
        try {
        sys.setRules( "Q = R+[Q+U]--//[--T]R[++T]-[QU]++QU\n"
                + "R = FS[//&&T][//^^T]FS\n"
                + "S = SFS\n"
                + "T = ['{+f.-ff.-f.+ | +f.-ff.-f.}]\n"
                + "U = [&&&V'/W////W////W////W////W]\n"
                + "V = FF\n"
                + "W = ['^F][{&&&&-f.+f.|-f.+f.}]\n");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemPlant3D2.getText(),tabPane));
   
    }//GEN-LAST:event_jMenuItemPlant3D2ActionPerformed

    private void jMenuItemHilbert3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHilbert3DActionPerformed

        LSystem sys = new LSystem();
        sys.setAxiom("X");
        sys.setAngleStep(90.0);
        sys.setThickness(0.15);
        sys.setColorSet(LSystem.COLORSET_EXTENDED);
        try {
        sys.setRules( "X = ''^\\XF^\\XFX-F^//XFX&F+//XFX-F/X-/\n");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemHilbert3D.getText(),tabPane));
   
    }//GEN-LAST:event_jMenuItemHilbert3DActionPerformed

    private void jMenuItemHG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHG1ActionPerformed

        LSystem sys = new LSystem();
        sys.setAxiom("F1F1F1");
        sys.setIgnoredSymbols("+-F");
        sys.setAngleStep(22.5);
        sys.setThickness(0.15);
        sys.setColorSet(LSystem.COLORSET_BASIC);
        try {
        sys.setRules( "0<0>0 = 0\n"
                + "0<0>1 = 1[+F1F1]\n"
                + "0<1>0 = 1\n"
                + "0<1>1 = 1\n"
                + "1<0>0 = 0\n"
                + "1<0>1 = 1F1\n"
                + "1<1>0 = 0\n"
                + "1<1>1 = 0\n"
                + "");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemHG1.getText(),tabPane));
   
    }//GEN-LAST:event_jMenuItemHG1ActionPerformed

    private void jMenuItemHG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHG2ActionPerformed

        LSystem sys = new LSystem();
        sys.setAxiom("F0F1F1");
        sys.setIgnoredSymbols("+-F");
        sys.setAngleStep(25.75);
        sys.setThickness(0.15);
        sys.setColorSet(LSystem.COLORSET_BASIC);
        try {
        sys.setRules( "0<0>0 = 1\n"
                    + "0<0>1 = 0\n"
                    + "0<1>0 = 0\n"
                    + "0<1>1 = 1F1\n"
                    + "1<0>0 = 1\n"
                    + "1<0>1 = 1[+F1F1]\n"
                    + "1<1>0 = 1\n"
                    + "1<1>1 = 0\n"
                    + "");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemHG2.getText(),tabPane));
   
    }//GEN-LAST:event_jMenuItemHG2ActionPerformed

    private void jMenuItemPlant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPlant1ActionPerformed

        LSystem sys = new LSystem();
        sys.setAxiom("F");
        sys.setAngleStep(20.0);
        sys.setThickness(0.15);
        sys.setColorSet(LSystem.COLORSET_BASIC);
        try {
        sys.setRules( "F = F[+F]F[-F][F]\n");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemPlant1.getText(),tabPane));
   
    }//GEN-LAST:event_jMenuItemPlant1ActionPerformed

    private void jMenuItemPlant5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPlant5ActionPerformed

        LSystem sys = new LSystem();
        sys.setAxiom("X");
        sys.setAngleStep(22.5);
        sys.setThickness(0.15);
        sys.setColorSet(LSystem.COLORSET_BASIC);
        try {
        sys.setRules( "X = F-[[X]+X]+F[+FX]-X\n"
                + "F=FF\n");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemPlant5.getText(),tabPane));
   
    }//GEN-LAST:event_jMenuItemPlant5ActionPerformed

    private void jMenuItemPenroseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPenroseActionPerformed

        LSystem sys = new LSystem();
        sys.setAxiom("[N]++[N]++[N]++[N]++[N]");
        sys.setAngleStep(36.0);
        sys.setThickness(0.05);
        sys.setColorSet(LSystem.COLORSET_BASIC);
        try {
        sys.setRules( "M = O++P----N[-O----M]++\n"
                + "N = +O--P[---M--N]+\n"
                + "O = -M++N[+++O++P]-\n"
                + "P = --O++++M[+P++++N]--N\n");
        } catch (LsysException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LPanel panel = new LPanel(sys);
        tabPane.addTab(null, panel);
        //prepne aktivitu na vytvoreny tab
        tabPane.setSelectedIndex(tabPane.getTabCount()-1);
        //nastavim headline
        tabPane.setTabComponentAt(tabPane.getSelectedIndex(), new LPanelHeadline(jMenuItemPenrose.getText(),tabPane));
   
    }//GEN-LAST:event_jMenuItemPenroseActionPerformed

    
    private void saveAs(){
        
        JFileChooser fileChooser = new JFileChooser(){

            @Override
            public void approveSelection(){
                    //pokud soubor existuje tak se zeptam jestli ho chce prepsat
                    if(getSelectedFile().exists()){
                            int i = JOptionPane.showConfirmDialog(this,"Soubor existuje, přepsat?", "Existující soubor",JOptionPane.YES_NO_CANCEL_OPTION);
                            switch(i){
                                    case JOptionPane.YES_OPTION:
                                            super.approveSelection();
                                            return;
                                    case JOptionPane.NO_OPTION:
                                            return;
                                    case JOptionPane.CANCEL_OPTION:
                                            cancelSelection();
                                            return;
                            }
                    }
                    super.approveSelection();
            }
        };
        
        int retval=fileChooser.showSaveDialog(this);
        
        if(retval == JOptionPane.YES_OPTION){
            
            //nastavim kam ukladat
            ((LPanel)tabPane.getSelectedComponent()).saveFile = fileChooser.getSelectedFile();
            
            //ulozim
            BufferedWriter out = null;
            try {
                out = new BufferedWriter(new FileWriter(((LPanel)tabPane.getSelectedComponent()).saveFile));
                out.write(((LPanel)tabPane.getSelectedComponent()).getLSys().toXML());

            } catch ( LsysException | IOException ex) {
		JOptionPane.showMessageDialog(this,"Nepovedlo se ulozit do souboru.",
					    "Error",
					    JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    out.close();
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            //zmenim jmeno v hlavicce
            ((LPanelHeadline)tabPane.getTabComponentAt(tabPane.getSelectedIndex())).setName(fileChooser.getSelectedFile().getName());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame inst = new MainFrame();
		inst.setLocationRelativeTo(null);
		inst.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemBush;
    private javax.swing.JMenuItem jMenuItemDragon;
    private javax.swing.JMenuItem jMenuItemHG1;
    private javax.swing.JMenuItem jMenuItemHG2;
    private javax.swing.JMenuItem jMenuItemHilbert;
    private javax.swing.JMenuItem jMenuItemHilbert3D;
    private javax.swing.JMenuItem jMenuItemKochStar;
    private javax.swing.JMenuItem jMenuItemKonec;
    private javax.swing.JMenuItem jMenuItemManual;
    private javax.swing.JMenuItem jMenuItemNovy;
    private javax.swing.JMenuItem jMenuItemOProgramu;
    private javax.swing.JMenuItem jMenuItemOtevrit;
    private javax.swing.JMenuItem jMenuItemPeano;
    private javax.swing.JMenuItem jMenuItemPeanoGosper;
    private javax.swing.JMenuItem jMenuItemPenrose;
    private javax.swing.JMenuItem jMenuItemPlant1;
    private javax.swing.JMenuItem jMenuItemPlant2;
    private javax.swing.JMenuItem jMenuItemPlant3;
    private javax.swing.JMenuItem jMenuItemPlant3D1;
    private javax.swing.JMenuItem jMenuItemPlant3D2;
    private javax.swing.JMenuItem jMenuItemPlant4;
    private javax.swing.JMenuItem jMenuItemPlant5;
    private javax.swing.JMenuItem jMenuItemSierpCarpet;
    private javax.swing.JMenuItem jMenuItemSierpTriangle;
    private javax.swing.JMenuItem jMenuItemUlozit;
    private javax.swing.JMenuItem jMenuItemUlozitJako;
    private javax.swing.JMenuItem jMenuItemZavriAkt;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private lmodeler.LPanel lPanel1;
    private javax.swing.JTabbedPane tabPane;
    // End of variables declaration//GEN-END:variables
}
